const AGGREGATORS = ['all', 'any']
const ATTRIBUTE_CODE = /^[A-Za-z][A-Za-z0-9_]*$/
const OPERATORS = ['eq', 'neq', 'in', 'nin', 'gt', 'gte', 'lt', 'lte']
const NUMERIC_OPERATORS = ['gt', 'gte', 'lt', 'lte']
const DEFAULT_PRIORITY = 100
const DEFAULT_CACHE_TTL = 300
const MAX_LIST_VALUES = 500
const MAX_GROUP_DEPTH = 3
const DEFAULT_PRODUCTS_TO_DISPLAY = 10
const MAX_PRODUCTS_TO_DISPLAY = 50
const DEFAULT_BLOCK_TYPE = 'littlefarms_featured_recommended'
const BLOCK_TYPES = [DEFAULT_BLOCK_TYPE]

module.exports = {
  AGGREGATORS,
  ATTRIBUTE_CODE,
  OPERATORS,
  NUMERIC_OPERATORS,
  DEFAULT_PRIORITY,
  DEFAULT_CACHE_TTL,
  MAX_LIST_VALUES,
  MAX_GROUP_DEPTH,
  DEFAULT_PRODUCTS_TO_DISPLAY,
  MAX_PRODUCTS_TO_DISPLAY,
  DEFAULT_BLOCK_TYPE,
  BLOCK_TYPES
}
